baseurl = "marce10.github.io/coded_bioacustics/"
DefaultContentLanguage = "en"
title = "Coded bioacoustics"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "maRce_10"
googleAnalytics = "G-RZVLSR0L9P"
enableEmoji = true
ignoreFiles = [ "\\.Rmd$", "\\.qmd$", "\\.ipynb$", "\\.py$" ]
[markup.goldmark.renderer]
unsafe= true

[Params]
  homeTitle = "Coded bioacoustics" # Set a different text for the header on the home page
  subtitle = "Code for the analysis of nature's sounds"
  mainSections = ["post","posts"]
  logo = "img/blog_sticker_v2.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/cod_bio.jpg"
#  position: 25% 75%;
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  params.author.name = "Marcelo Araya-Salas"
  website = "https://marce10.github.io"
  params.author.email = "marcelo.araya@ucr.ac.cr"
#  facebook = "username"
  github = "maRce10"
#  gitlab = "username"
#  bitbucket = "username"
  twitter = "Marcelo_Araya_Salas"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
 stackoverflow = "users/4178065/marcelo-araya-salas"
#  snapchat = "username"
#  instagram = "username"
  youtube = "@MarRce10" # or channel/channelname
# soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"
#  discord = "invite code (https://discord.gg/XXXXXXX)"
#  strava = "userid"

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "Useful resources"
    name = "Useful resources"
    weight = 2

 [[menu.main]]
    parent = "Useful resources"
    name = "Bioacoustics software list"
    url = "https://github.com/rhine3/bioacoustics-software"
   weight = 1

 [[menu.main]]
    parent = "Useful resources"
    name = "Bioacoustics StackExcange forum"
    url = "https://bioacoustics.stackexchange.com/"
    weight = 2

 [[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'
    disable = false

  [markup.highlight]
  style = 'friendly'

  [[module.mounts]]
  source = 'assets'
  target = 'assets'

  [[module.mounts]]
  source = 'static'
  target = 'assets'

[markup]
  defaultMarkdownHandler = 'goldmark'

[services]
  [services.disqus]
    shortname = 'maRce_10'


